# Generated by Django 4.2.7 on 2024-01-15 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='canton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_canton', models.CharField(max_length=225, null=True)),
            ],
            options={
                'verbose_name': 'nombre_canton',
                'verbose_name_plural': 'nombre_cantones',
                'ordering': ['nombre_canton'],
            },
        ),
        migrations.CreateModel(
            name='hospedaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_hospedaje', models.CharField(max_length=225, null=True)),
                ('fotoHospedaje', models.ImageField(null=True, upload_to='')),
                ('direccionHospedaje', models.URLField(null=True)),
                ('horario', models.CharField(max_length=225, null=True)),
                ('tipoHospedaje', models.CharField(max_length=225, null=True)),
                ('categoria', models.CharField(max_length=225, null=True)),
                ('canton_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.canton')),
            ],
            options={
                'verbose_name': 'hospedaje',
                'verbose_name_plural': 'hospedajes',
                'ordering': ['nombre_hospedaje'],
            },
        ),
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nomEvento', models.CharField(max_length=225, null=True)),
                ('fechaEvento', models.DateTimeField(null=True)),
                ('direccionEvento', models.URLField(null=True)),
                ('infoEvento', models.TextField(max_length=225, null=True)),
                ('fotoEvento', models.ImageField(null=True, upload_to='')),
                ('canton_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.canton')),
            ],
            options={
                'verbose_name': 'eventos',
                'verbose_name_plural': 'eventos',
                'ordering': ['nomEvento'],
            },
        ),
    ]
