# Generated by Django 4.2.7 on 2024-01-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_lugares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='fechaEvento',
            new_name='fecha_fin',
        ),
        migrations.AddField(
            model_name='eventos',
            name='fecha_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
