# Generated by Django 4.2.7 on 2024-01-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_rename_fechaevento_eventos_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospedaje',
            name='horario',
        ),
        migrations.AddField(
            model_name='hospedaje',
            name='fecha_fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hospedaje',
            name='fecha_inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hospedaje',
            name='infoHospedaje',
            field=models.TextField(null=True),
        ),
    ]
