# Generated by Django 4.2.7 on 2024-01-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_remove_hospedaje_horario_hospedaje_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospedaje',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='hospedaje',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='hospedaje',
            name='hora_abre',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='hospedaje',
            name='hora_cierra',
            field=models.TimeField(null=True),
        ),
    ]
