# Generated by Django 4.2.7 on 2024-01-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_remove_hospedaje_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedaje',
            name='precioNoche',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
    ]
